### ISSUE TITLE
在 intel cpu 的 mac 下，如何编译？

### ISSUE THREAD

**Issue by sarrow104** [SaeruHikari/SakuraEngine#2]
[cmake] -- Use CLANG Compiler Clang
[cmake] CMake Error at cmake/Network.cmake:15 (message):
[cmake]   Error downloading
[cmake]   http://139.59.27.159//SaeruHikari/binaries/mac/x64/common/dxc.zip: "HTTP
[cmake]   response code said error" (22)
[cmake] Call Stack (most recent call first):
[cmake]   cmake/Network.cmake:20 (download_file)
[cmake]   SakuraEngine/Source/Development/ShaderCompiler/CMakeLists.txt:3 (download_and_extract)

该url是404；同样目录下，只是有一个ispc.**.zip 文件，可以下载；

另外，这个 dxc.zip 是做什么用的？

**Comment by SaeruHikari** [comment]
dxc是d3d的新跨平台shader编译器。
macos版本的dxc暂时未推送，并且引擎很久没在macos上测试过了。
引擎本身目前在闭源开发中，本仓库的代码暂时停止更新，仅用来托管boids demo。引擎会在比较完善的情况下重新利用本仓库开源。
如果想运行demo，考虑在windows上build。

**Comment by sarrow104** [comment]
ok
